WillFerrellTop30ish/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WillFerrellTop30ish.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
    }
}

WillFerrellTop30ish/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Helpers;
using WillFerrellTop30ish.Models;

namespace WillFerrellTop30ish.Controllers
{
    public class StaffController : Controller
    {
        DAO dao = new DAO();

        //IsStaffActive is made available in controllers that have access
        //to adminstrative Methods, this is to ensure that no deactivated
        //staff members, who were deactivated after a successful login and 
        //still have an active session. It will be used to contole the 
        //closure of their session in such a case.
        private bool IsStaffActive(string email)
        {
            Staff staff = dao.SelectOneStaff(email);
            return staff.IsActive;
        }

        //Method to ensure that Session state is valid (userType is staff with an email set).
        //Also checks IsActive state from the db to ensure that staff member was not
        //deactivated. If Session state is invalid or the currently logged in staff member
        //has since been deactivated, the session will be cleared. Thus ensuring only properly
        //logged in staff members will be able to access certain pages.
        private bool IsStaffSessionValid()
        {
            if (Session != null)
            {
                if (Session["userType"] != null)
                {
                    if (Session["userType"].ToString() == "staff")
                    {
                        if (Session["email"].ToString() != null)
                        {
                            if (!IsStaffActive(Session["email"].ToString()))
                            {
                                Session.Clear();
                                return false;
                            }
                        }
                        else
                        {
                            Session.Clear();
                            return false;
                        }
                    }
                }
                else
                {
                    Session.Clear();
                    return false;
                }
            }
            else //If Session == null, then StaffSession is not valid
            {
                return false;
            }
            return true;
        }

        // GET: Staff
        public ActionResult Index()
        {
            IsStaffSessionValid();
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            IsStaffSessionValid();
            return View();
        }

        [HttpPost]
        public ActionResult Login(Staff staff)
        {
            ModelState.Remove("IsActive");
            if (ModelState.IsValid)
            {
                Staff staffRecord = dao.SelectOneStaff(staff.Email);
                if (staffRecord != null)
                {
                    if (staff.Email == staffRecord.Email)
                    {
                        //This will only happen on first time login at which time we want to hash the password
                        if (staff.Password == staffRecord.Password)
                        {
                            staffRecord.Password = Crypto.HashPassword(staff.Password);
                            dao.UpdateStaff(staffRecord);
                        }

                        if (Crypto.VerifyHashedPassword(staffRecord.Password, staff.Password))
                        {
                            if (staffRecord.IsActive)
                            {
                                Session.Clear();
                                Session["userType"] = "staff";
                                Session["email"] = staff.Email;
                                return RedirectToAction("Index");
                            }
                            else
                            {
                                ViewBag.Message = "This account was deactivated, please contact an admin.";
                            }
                        }
                        else
                        {
                            ViewBag.Message = "The Email and Password Combination entered do not match any Staff records.";
                        }
                    }
                    else
                    {
                        ViewBag.Message = "The Email and Password Combination entered do not match any Staff records.";
                    }
                }
                else
                {
                    ViewBag.Message = "The Email and Password Combination entered do not match any Staff records.";
                }
            }
            else
            {
                ViewBag.Message = "You must enter valid data in the form.";
            }
            return View();
        }

        [HttpGet]
        public ActionResult Logout()
        {
            if (Session["userType"] != null && Session["userType"].ToString() == "staff")
            {
                Session.Clear();
            }
            return RedirectToAction("Login");
        }

        [HttpGet]
        public ActionResult List()
        {
            List<Staff> staffList = null;
            if (IsStaffSessionValid())
            {
                staffList = dao.SelectAllStaff();
                return View(staffList);
            }
            else
            {
                return View(staffList);
            }
        }

        [HttpGet]
        public ActionResult ChangePassword()
        {
            IsStaffSessionValid();
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(FormCollection form)
        {
            Staff staffRecord = dao.SelectOneStaff(Session["email"].ToString());

            if (Crypto.VerifyHashedPassword(staffRecord.Password, form["txtCurrPassword"]))
            {
                staffRecord.Password = Crypto.HashPassword(form["txtNewPassword1"]);
                dao.UpdateStaff(staffRecord);
                ViewBag.Message = "Password Changed Successfully";
                return View();
            }
            else
            {
                ViewBag.Message = "The password you entered for Current Password does not match the stored password";
                return View();
            }
        }

        [HttpGet]
        public ActionResult AddStaff()
        {
            IsStaffSessionValid();
            return View();
        }

        [HttpPost]
        public ActionResult AddStaff(Staff staff)
        {
            staff.IsActive = true;
            staff.Password = Crypto.HashPassword(staff.Password);
            if (dao.InsertStaff(staff) == 1)
            {
                ViewBag.Message = "Staff member successfully added.";
                return View();
            }
            else
            {
                ViewBag.Message = "Something went wrong... Staff member not added.";
                return View();
            }
        }

        [HttpGet]
        public ActionResult DeleteStaff()
        {
            IsStaffSessionValid();
            return View();
        }

        [HttpPost]
        public ActionResult DeleteStaff(Staff staff)
        {
            IsStaffSessionValid();
            dao.DeleteStaffMember(staff.Email);
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult DeactivateStaff()
        {
            IsStaffSessionValid();
            return View();
        }

        [HttpPost]
        public ActionResult DeactivateStaff(Staff staff)
        {
            IsStaffSessionValid();
            staff.IsActive = false;
            dao.UpdateStaff(staff);
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult ActivateStaff()
        {
            IsStaffSessionValid();
            return View();
        }

        [HttpPost]
        public ActionResult ActivateStaff(Staff staff)
        {
            IsStaffSessionValid();
            staff.IsActive = true;
            dao.UpdateStaff(staff);
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult ResetPass()
        {
            IsStaffSessionValid();
            return View();
        }

        [HttpPost]
        public ActionResult ResetPass(Staff staff)
        {
            IsStaffSessionValid();
            staff.Password = Crypto.HashPassword("admin");
            dao.UpdateStaff(staff);
            return RedirectToAction("List");
        }
    }
}

WillFerrellTop30ish/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Will Ferrell's Top 30ish Movies</title>
    <link rel="stylesheet" type="text/css" href="~/Content/Styles.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Karla" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
        function getCookie(cName) {
            var name = cName + "=";
            var decodedCookie = decodeURIComponent(document.cookie);
            var cookieArr = decodedCookie.split(';');
            for (var i = 0; i < cookieArr.length; i++) {
                var c = cookieArr[i];
                if (c.indexOf(name) !== -1) {
                    return c.substring(c.indexOf(name)+cName.length+1)
                }
            }
            return "";
        }

        function checkCookieState() {
            var cartCookieVal = getCookie("cart");
            if (cartCookieVal !== "") {
                var titlesInCart = cartCookieVal.split(':');
                var titleQty = 0;
                for (var i = 0; i < titlesInCart.length; i++) {
                    titleQty += parseInt(titlesInCart[i].split('_')[1]);
                }
                if (titleQty > 0) {
                    $("#cartQty").html("(" + titleQty + ") - SHOPPING CART");
                }

            }


        }

        function cookieExists(cName) {
            var cookie = getCartCookie(cName);
            if (cookie !== "") {
                return true;
            }
            else {
                return false;
            }

        }

        function addToCart(titleID) {
            var qty = parseInt($("#txtQuantity" + titleID).val());
            console.log("qty=" + qty);
            if (qty > 0) {
                var cookie = getCookie("cart");
                if (cookie !== "") {
                    var d = new Date();
                    d.setTime(d.getTime() + (10 * 24 * 60 * 60 * 1000));//cookie lasts 10 days
                    var expires = "; expires=" + d.toUTCString();
                    var qty = parseInt($("#txtQuantity" + titleID).val());
                    var itemInCart = false;
                    var cart = "cart=";
                    var itemsInCart = cookie.split(':');
                    var newItemsInCart = new Array();
                    for (var i = 0; i < itemsInCart.length; i++) {
                        item = itemsInCart[i].split('_');
                        if (item[0] === titleID) {
                            itemInCart = true;
                            item[1] = parseInt(item[1]) + qty;
                        }
                        newItemsInCart.push(item[0] + "_" + item[1]);
                    }
                    if (!itemInCart) {
                        newItemsInCart.push(titleID + "_" + qty);
                    }
                    cart = cart + newItemsInCart.join(":");
                    document.cookie = cart + expires + "; path=/";
                }
                else {
                    var d = new Date();
                    d.setTime(d.getTime() + (10 * 24 * 60 * 60 * 1000));//cookie lasts 10 days
                    var expires = "; expires=" + d.toUTCString();
                    document.cookie = "cart=" + titleID + "_" + qty + expires + "; path=/";
                }
            }
            checkCookieState();
        }

        function updateItemInCart(titleID, qty) {
            var cookie = getCookie("cart");
            var itemsInCart = cookie.split(':');
            var newItemsInCart = new Array();
            var cart = "cart=";
            var d = new Date();
            d.setTime(d.getTime() + (10 * 24 * 60 * 60 * 1000));//cookie lasts 10 days
            var expires = "; expires=" + d.toUTCString();
            for (var i = 0; i < itemsInCart.length; i++) {
                item = itemsInCart[i].split('_');
                if (item[0] === titleID) {
                    newItemsInCart.push(item[0] + "_" + qty);
                }
                else {
                    newItemsInCart.push(item[0] + "_" + item[1]);
                }
            }
            cart = cart + newItemsInCart.join(":");
            document.cookie = cart + expires + "; path=/";
        }

        function removeFromCart(titleID) {
            var cookie = getCookie("cart");
            var itemsInCart = cookie.split(':');
            var newItemsInCart = new Array();
            for (var i = 0; i < itemsInCart.length; i++) {
                item = itemsInCart[i].split('_');
                if (item[0] !== titleID) {
                    newItemsInCart.push(item[0] + "_" + item[1]);
                }
            }

            if (newItemsInCart.length === 0) {
                var d = new Date();
                d.setTime(d.getTime() - 1);//expire cookie
            }
            else {
                var d = new Date();
                d.setTime(d.getTime() + (10 * 24 * 60 * 60 * 1000));//cookie lasts 10 days
            }
            var expires = "; expires=" + d.toUTCString();
            document.cookie = "cart=" + newItemsInCart.join(':') + expires + "; path=/";
        }

        function emptyCart() {
            var d = new Date();
            d.setTime(d.getTime() - 1);//expire cookie
            var expires = "; expires=" + d.toUTCString();
            document.cookie = "cart=" + expires + "; path=/";
        }
    </script>
</head>
<body onload="checkCookieState()">
    @RenderSection("logged", false)


    <div class="container">
        <img src="~/Content/imgs/burgundy-banner.png" title="ron burgundy" alt="pic of ron">
        <div class="centered">Will Ferrell's top 30ish Movies</div>
    </div>

    <div class="navbar">
        @Html.ActionLink("Home", "Index", "Home")
        @Html.ActionLink("Movies", "Index", "Movies")
        @Html.ActionLink("About Us", "Index", "About")
        <div class="topnav-right">
            @Html.ActionLink("Shopping Cart", "Cart", "Order", null, new { id = "cartQty" })
            @Html.ActionLink("Account", "Index", "Customer")
        </div>
    </div>
    <div id="divBreadcrumb">
        You are here: @Html.MvcSiteMap().SiteMapPath()
        @if (Session != null && Session["userType"] != null && Session["userType"].ToString() == "staff")
        {
            <span class="right">
                @Html.ActionLink("Staff Index", "Index", "Staff") -
                @Html.ActionLink("Logout", "Logout", "Staff")
            </span>
        }
        else if (Session != null && Session["userType"] != null && Session["userType"].ToString() == "customer")
        {
            <span class="right">
                @Html.ActionLink("Logout", "Logout", "Customer")
            </span>
        }

    </div>

    <br />
    <br>



    <div class="wrapper">



        <main>
            @RenderBody()
        </main>
    </div>


    <footer>
        <div class="footer">
            <h4> We are social - don't forget to follow us!</h4>
            <a href="https://www.facebook.com" class="fa fa-facebook"></a>
            <a href="https://www.twitter.com" class="fa fa-twitter"></a>
            <a href="https://www.instagram.com" class="fa fa-instagram"></a>
            <br />
            &copy; @DateTime.Now.Year - WillFerrellTop30ish
        </div>
        <br />

    </footer>

</body>
</html>