WillFerrellTop30ish/Models/Staff.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace WillFerrellTop30ish.Models
{

    public class Staff
    {
        [Required]
        public string Email { get; set; }
        [Required]
        public string Password { get; set; }
        public bool IsActive { get; set; }
    }
}

WillFerrellTop30ish/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Helpers;
using WillFerrellTop30ish.Models;
using System.Xml;

namespace WillFerrellTop30ish.Controllers
{
    public class MoviesController : Controller
    {
        DAO dao = new DAO();

        //IsStaffActive is made available in controllers that have access
        //to adminstrative Methods, this is to ensure that no deactivated
        //staff members, who were deactivated after a successful login and 
        //still have an active session. It will be used to contole the 
        //closure of their session in such a case.
        private bool IsStaffActive(string email)
        {
            Staff staff = dao.SelectOneStaff(email);
            return staff.IsActive;
        }

        // GET: Movies
        public ActionResult Index()
        {
            if (Session["userType"] != null)
            {
                if (Session["userType"].ToString() == "staff")
                {
                    if (Session["email"].ToString() != null)
                    {
                        if (!IsStaffActive(Session["email"].ToString()))
                        {
                            Session.Clear();
                        }
                    }
                    else
                    {
                        Session.Clear();
                    }
                }
            }
            List<Movie> list = dao.ShowAllMovies();
            return View(list);
        }


        [HttpGet]
        public ActionResult Add()
        {
            if (Session["userType"] != null)
            {
                if (Session["userType"].ToString() == "staff")
                {
                    if (Session["email"].ToString() != null)
                    {
                        if (!IsStaffActive(Session["email"].ToString()))
                        {
                            Session.Clear();
                        }
                    }
                    else
                    {
                        Session.Clear();
                    }
                }
            }
            return View();
        }

        [HttpPost]
        public ActionResult Add(Movie movie)
        {
            if (Session["userType"] != null)
            {
                if (Session["userType"].ToString() == "staff")
                {
                    if (Session["email"].ToString() != null)
                    {
                        if (!IsStaffActive(Session["email"].ToString()))
                        {
                            Session.Clear();
                            return View();
                        }
                    }
                    else
                    {
                        Session.Clear();
                        return View();
                    }
                }
            }
            int counter = 0;
            counter = dao.InsertMovie(movie);
            if (counter == 1)
            {
                ViewBag.Message = "Record inserted successfully";
                ModelState.Clear();
            }
            else
            {
                ViewBag.Message = "Error, " + dao.message;
            }

            return View();
        }

        [HttpPost]
        public ActionResult Delete(string ID)
        {
            if (Session["userType"] != null)
            {
                if (Session["userType"].ToString() == "staff")
                {
                    if (Session["email"].ToString() != null)
                    {
                        if (!IsStaffActive(Session["email"].ToString()))
                        {
                            Session.Clear();
                            return RedirectToAction("Index");
                        }
                    }
                    else
                    {
                        Session.Clear();
                        return RedirectToAction("Index");
                    }
                }
                //Guard against deletion request by customer
                else
                {
                    return RedirectToAction("Index");
                }
            }
            //do not delete if no session exists, return to index
            else
            {
                return RedirectToAction("Index");
            }
            dao.DeleteMovie(ID);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ShowOne(string id)
        {
            Movie movie = dao.ShowOneMovie(id);
            return View(movie);
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            if (Session["userType"] != null)
            {
                if (Session["userType"].ToString() == "staff")
                {
                    if (Session["email"].ToString() != null)
                    {
                        if (!IsStaffActive(Session["email"].ToString()))
                        {
                            Session.Clear();
                        }
                    }
                    else
                    {
                        Session.Clear();
                    }
                }
            }
            Movie movie = dao.ShowOneMovie(id);
            return View(movie);
        }

        [HttpPost]
        public ActionResult Edit(Movie movie)
        {
            if (ModelState.IsValid)
            {
                dao.UpdateMovie(movie);
                return RedirectToAction("Index");
            }

            return View(movie);
        }

    }
}

WillFerrellTop30ish/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Helpers;
using WillFerrellTop30ish.Models;

namespace WillFerrellTop30ish.Controllers
{
    public class StaffController : Controller
    {
        DAO dao = new DAO();

        //IsStaffActive is made available in controllers that have access
        //to adminstrative Methods, this is to ensure that no deactivated
        //staff members, who were deactivated after a successful login and 
        //still have an active session. It will be used to contole the 
        //closure of their session in such a case.
        private bool IsStaffActive(string email)
        {
            Staff staff = dao.SelectOneStaff(email);
            return staff.IsActive;
        }

        //Method to ensure that Session state is valid (userType is staff with an email set).
        //Also checks IsActive state from the db to ensure that staff member was not
        //deactivated. If Session state is invalid or the currently logged in staff member
        //has since been deactivated, the session will be cleared. Thus ensuring only properly
        //logged in staff members will be able to access certain pages.
        private bool IsStaffSessionValid()
        {
            if (Session != null)
            {
                if (Session["userType"] != null)
                {
                    if (Session["userType"].ToString() == "staff")
                    {
                        if (Session["email"].ToString() != null)
                        {
                            if (!IsStaffActive(Session["email"].ToString()))
                            {
                                Session.Clear();
                                return false;
                            }
                        }
                        else
                        {
                            Session.Clear();
                            return false;
                        }
                    }
                }
                else
                {
                    Session.Clear();
                    return false;
                }
            }
            else //If Session == null, then StaffSession is not valid
            {
                return false;
            }
            return true;
        }

        // GET: Staff
        public ActionResult Index()
        {
            IsStaffSessionValid();
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            IsStaffSessionValid();
            return View();
        }

        [HttpPost]
        public ActionResult Login(Staff staff)
        {
            ModelState.Remove("IsActive");
            if (ModelState.IsValid)
            {
                Staff staffRecord = dao.SelectOneStaff(staff.Email);
                if (staffRecord != null)
                {
                    if (staff.Email == staffRecord.Email)
                    {
                        //This will only happen on first time login at which time we want to hash the password
                        if (staff.Password == staffRecord.Password)
                        {
                            staffRecord.Password = Crypto.HashPassword(staff.Password);
                            dao.UpdateStaff(staffRecord);
                        }

                        if (Crypto.VerifyHashedPassword(staffRecord.Password, staff.Password))
                        {
                            if (staffRecord.IsActive)
                            {
                                Session.Clear();
                                Session["userType"] = "staff";
                                Session["email"] = staff.Email;
                                return RedirectToAction("Index");
                            }
                            else
                            {
                                ViewBag.Message = "This account was deactivated, please contact an admin.";
                            }
                        }
                        else
                        {
                            ViewBag.Message = "The Email and Password Combination entered do not match any Staff records.";
                        }
                    }
                    else
                    {
                        ViewBag.Message = "The Email and Password Combination entered do not match any Staff records.";
                    }
                }
                else
                {
                    ViewBag.Message = "The Email and Password Combination entered do not match any Staff records.";
                }
            }
            else
            {
                ViewBag.Message = "You must enter valid data in the form.";
            }
            return View();
        }

        [HttpGet]
        public ActionResult Logout()
        {
            if (Session["userType"] != null && Session["userType"].ToString() == "staff")
            {
                Session.Clear();
            }
            return RedirectToAction("Login");
        }

        [HttpGet]
        public ActionResult List()
        {
            List<Staff> staffList = null;
            if (IsStaffSessionValid())
            {
                staffList = dao.SelectAllStaff();
                return View(staffList);
            }
            else
            {
                return View(staffList);
            }
        }

        [HttpGet]
        public ActionResult ChangePassword()
        {
            IsStaffSessionValid();
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(FormCollection form)
        {
            Staff staffRecord = dao.SelectOneStaff(Session["email"].ToString());

            if (Crypto.VerifyHashedPassword(staffRecord.Password, form["txtCurrPassword"]))
            {
                staffRecord.Password = Crypto.HashPassword(form["txtNewPassword1"]);
                dao.UpdateStaff(staffRecord);
                ViewBag.Message = "Password Changed Successfully";
                return View();
            }
            else
            {
                ViewBag.Message = "The password you entered for Current Password does not match the stored password";
                return View();
            }
        }

        [HttpGet]
        public ActionResult AddStaff()
        {
            IsStaffSessionValid();
            return View();
        }

        [HttpPost]
        public ActionResult AddStaff(Staff staff)
        {
            staff.IsActive = true;
            staff.Password = Crypto.HashPassword(staff.Password);
            if (dao.InsertStaff(staff) == 1)
            {
                ViewBag.Message = "Staff member successfully added.";
                return View();
            }
            else
            {
                ViewBag.Message = "Something went wrong... Staff member not added.";
                return View();
            }
        }

        [HttpGet]
        public ActionResult DeleteStaff()
        {
            IsStaffSessionValid();
            return View();
        }

        [HttpPost]
        public ActionResult DeleteStaff(Staff staff)
        {
            IsStaffSessionValid();
            dao.DeleteStaffMember(staff.Email);
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult DeactivateStaff()
        {
            IsStaffSessionValid();
            return View();
        }

        [HttpPost]
        public ActionResult DeactivateStaff(Staff staff)
        {
            IsStaffSessionValid();
            staff.IsActive = false;
            dao.UpdateStaff(staff);
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult ActivateStaff()
        {
            IsStaffSessionValid();
            return View();
        }

        [HttpPost]
        public ActionResult ActivateStaff(Staff staff)
        {
            IsStaffSessionValid();
            staff.IsActive = true;
            dao.UpdateStaff(staff);
            return RedirectToAction("List");
        }

        [HttpGet]
        public ActionResult ResetPass()
        {
            IsStaffSessionValid();
            return View();
        }

        [HttpPost]
        public ActionResult ResetPass(Staff staff)
        {
            IsStaffSessionValid();
            staff.Password = Crypto.HashPassword("admin");
            dao.UpdateStaff(staff);
            return RedirectToAction("List");
        }
    }
}

WillFerrellTop30ish/Views/Staff/ActivateStaff.cshtml
@{
    ViewBag.Title = "ActivateStaff";
}
@section logged{
    @if (Session == null || Session["userType"] == null || Session["userType"].ToString() != "staff")
    {
        Response.Redirect(Url.Action("Login", "Staff"));
    }

}

<h2>Oops! You shouldn't be here...</h2>

@Html.ActionLink("Go back to Staff Index", "Index", "Staff")

WillFerrellTop30ish/Views/Staff/AddStaff.cshtml
@model WillFerrellTop30ish.Models.Staff
@{
    ViewBag.Title = "AddStaff";
}
@section logged{
    @if (Session == null || Session["userType"] == null || Session["userType"].ToString() != "staff")
    {
        Response.Redirect(Url.Action("Login", "Staff"));
    }
}

<script>
    function verifyPasswordsMatch() {
        if ($("#txtStaffPass1").val() !== $("#txtStaffPass2").val()) {
            $("#spnNoMatchError").text("New passwords entered do not match each other.");
            return false;
        }
        return true;
    }
</script>
<h2>Add Staff</h2>

<h3>@ViewBag.Message</h3>

<span id="spnNoMatchError" style="color: red"></span>

@using (Html.BeginForm("AddStaff", "Staff", FormMethod.Post, new { id = "frmAddStaff", onsubmit = "return verifyPasswordsMatch()" }))
{
    <div class="form">
        <p>
            @Html.LabelFor(s => s.Email)
            @Html.TextBoxFor(s => s.Email, new { id = "txtStaffEmail", placeholder = "New staff email...", type = "email" })
            @Html.LabelFor(s => s.Password)<br />
            @Html.TextBoxFor(s => s.Password, new { id = "txtStaffPass1", type = "password" })<br />
            @Html.Label("Confirm Password")<br />
            @Html.TextBox("txtStaffPass2", null, new { type = "password" })<br />
        </p>
        <input type="submit" value="Add New Staff" />
    </div>
}

WillFerrellTop30ish/Views/Staff/ChangePassword.cshtml
@{
    ViewBag.Title = "ChangePassword";
}
@section logged{
    @if (Session == null || Session["userType"] == null || Session["userType"].ToString() != "staff")
    {
        Response.Redirect(Url.Action("Login", "Staff"));
    }
}

<script>
    function verifyNewPasswordsMatch() {
        if ($("#txtNewPassword1").val() !== $("#txtNewPassword2").val()) {
            $("#spnNoMatchError").text("New passwords entered do not match each other.");
            return false;
        }
        return true;
    }
</script>

<h2>ChangePassword</h2>

<h3>@ViewBag.Message</h3>

@using (Html.BeginForm("ChangePassword", "Staff", FormMethod.Post, new { id = "frmChangePassword", onsubmit = "return verifyNewPasswordsMatch()" }))
{
    <div id="divChangeStaffPassForm">
        <p>
            @Html.Label("lblCurrPassword", "Current Password")
            <br />
            @Html.Password("txtCurrPassword")
        </p>
        <span id="spnNoMatchError" style="color: red"></span>
        <p>
            @Html.Label("lblNewPassword1", "New Password")
            <br />
            @Html.Password("txtNewPassword1")
        </p>
        <p>
            @Html.Label("lblNewPassword2", "Repeat New Password")
            <br />
            @Html.Password("txtNewPassword2")
        </p>
        <input type="submit" value="Change Password" />
    </div>
}

WillFerrellTop30ish/Views/Staff/DeactivateStaff.cshtml
@{
    ViewBag.Title = "DeactivateStaff";
}

@section logged{
    @if (Session == null || Session["userType"] == null || Session["userType"].ToString() != "staff")
    {
        Response.Redirect(Url.Action("Login", "Staff"));
    }

}

<h2>Oops! You shouldn't be here...</h2>

@Html.ActionLink("Go back to Staff Index", "Index", "Staff")

WillFerrellTop30ish/Views/Staff/DeleteStaff.cshtml
@{
    ViewBag.Title = "DeleteStaff";
}
@section logged{
    @if (Session == null || Session["userType"] == null || Session["userType"].ToString() != "staff")
    {
        Response.Redirect(Url.Action("Login", "Staff"));
    }

}

<h2>Oops! You shouldn't be here...</h2>

@Html.ActionLink("Go back to Staff Index", "Index", "Staff")

WillFerrellTop30ish/Views/Staff/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@section logged{
    @if (Session == null || Session["userType"] == null || Session["userType"].ToString() != "staff")
    {
        Response.Redirect(Url.Action("Login", "Staff"));
    }
}

<h2>Staff Index</h2>

<div class="form">
    <h3>What would you like to do?</h3>
    <ul>
        <li>@Html.ActionLink("Work with Movies", "Index", "Movies")</li>
        <li>@Html.ActionLink("Work with Staff", "List", "Staff")</li>
        <li>@Html.ActionLink("Work With Customers", "CustomerAdministration", "Customer")</li>
        <li>@Html.ActionLink("Work with Orders", "AdministratorOrders", "Order")</li>
    </ul>
</div>

WillFerrellTop30ish/Views/Staff/List.cshtml
@model IEnumerable<WillFerrellTop30ish.Models.Staff>
@{
    ViewBag.Title = "List";
}

@section logged{
    @if (Session == null || Session["userType"] == null || Session["userType"].ToString() != "staff")
    {
        Response.Redirect(Url.Action("Login", "Staff"));
    }

}

@if (Session != null || Session["userType"] != null && Session["userType"].ToString() == "staff")
{
    <h2>Staff Administration</h2>

    <h3>@Html.ActionLink("Add Staff Member", "AddStaff")</h3>
    <hr />
    <br />

    @* Two loops used to traverse through model. *@

    @*First loop, used to display currently logged in staff member only, as options are different.
        For example a staff member cannot delete their own account or set their status as not active*@
    foreach (var staff in Model)
    {
        if (staff.Email == Session["Email"].ToString())
        {
            <h3>Your details</h3>

            <div id="currentStaffMember">
                <p>
                    Email: @staff.Email
                    @Html.ActionLink("Change Password", "ChangePassword")
                </p>
            </div>

        }
    }

    <br />
    <hr />
    <br />


    @*Second loop, used to display list of other staff members. These can be set as not active or deleted.*@
    <h3>Other Staff Member Details</h3>

    <div id="otherStaffMembers" class="center">
        <table>
            <thead>
                <tr>
                    <th>Email Address</th>
                    <th>IsActive</th>
                    <th>Change Active Status</th>
                    <th>Reset Password</th>
                    <th>Delete Staff</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var staff in Model)
                {

                    if (staff.Email != Session["Email"].ToString())
                    {

                        <tr>
                            <td>@staff.Email</td>
                            <td>@staff.IsActive</td>
                            <td>
                                @if (staff.IsActive)
                                {
                                    using (Html.BeginForm("DeactivateStaff", "Staff", staff))
                                    {
                                        <input type="submit" value="Deactivate Staff Member" onclick="return confirm('Are you sure you want to deactivate this Staff Member\'s account?')" />
                                    }
                                }
                                else
                                {
                                    using (Html.BeginForm("ActivateStaff", "Staff", staff))
                                    {
                                        <input type="submit" value="Activate Staff Member" onclick="return confirm('Are you sure you want to activate this Staff Member\'s account?')" />
                                    }
                                }
                            </td>
                            <td>
                                @using (Html.BeginForm("ResetPass", "Staff", staff))
                                {
                                    <input type="submit" value="Reset Password" onclick="return confirm('Staff members password will be reset to \'admin\'?')" />
                                }
                            </td>
                            <td>
                                @using (Html.BeginForm("DeleteStaff", "Staff", staff))
                                {
                                    <input type="submit" value="Delete Staff Member" onclick="return confirm('Are you sure you want to delete this Staff Member?')" />
                                }
                            </td>
                        </tr>

                    }
                }
            </tbody>
        </table>
    </div>

}

WillFerrellTop30ish/Views/Staff/Login.cshtml
@model WillFerrellTop30ish.Models.Staff
@{
    ViewBag.Title = "Login";
}
@if (Session == null || Session["userType"] == null || Session["userType"].ToString() != "staff")
{
    <h2>Login</h2>

    <h3>@ViewBag.Message</h3>

    <div id="divLoginForm">
        @using (Html.BeginForm("Login", "Staff", FormMethod.Post, new { id = "frmStaffLogin" }))
        {
            <p>
                <!--Staff Email-->
                @Html.LabelFor(s => s.Email)
                @Html.TextBoxFor(s => s.Email, new { id = "txtStaffEmail", type = "email" })
            </p>
            <p>
                <!--Staff Pass-->
                @Html.LabelFor(s => s.Password)<br />
                @Html.TextBoxFor(s => s.Password, new { id = "txtStaffPass", type = "password" })
            </p>
            <br />

            <input id="Submit" type="submit" value="submit" />
            <input id="Reset" type="reset" value="reset" />
        }
    </div>
}
else
{
    <h2>Login</h2>

    <h3>You are currently logged in as staff member with email address @Session["email"].ToString()</h3>
}


<br />
<br />
<div class="quote">
    <img src="~/Content/imgs/will1.jpg" alt="Alex Trebek on SNL" />
    <h5>"I said let the boy watch!"</h5>
    <cite>Ashley Schaeffer - Eastbound & Down 2009</cite>
</div>

WillFerrellTop30ish/Views/Staff/ResetPass.cshtml
@{
    ViewBag.Title = "ResetPass";
}
@section logged{
    @if (Session == null || Session["userType"] == null || Session["userType"].ToString() != "staff")
    {
        Response.Redirect(Url.Action("Login", "Staff"));
    }

}

<h2>Oops! You shouldn't be here...</h2>

@Html.ActionLink("Go back to Staff Index", "Index", "Staff")